### ISSUE TITLE
Can't install on High Sierra

### ISSUE THREAD

**Issue by FIndustries** [JK3Y/asepsis#1]
I'm trying to install it on MacOS High Sierra (10.13.6) but I'm getting this error:

```
> "/Library/Application Support/Asepsis/ctl/asepsisctl" install
Asepsis ##VERSION## can be only installed under OS X versions 10.8, 10.9 and 10.10
Check out http://asepsis.binaryage.com for updated version.
```

**Comment by JK3Y** [comment]
Are you installing it by running `rake install`?

**Comment by FIndustries** [comment]
Yes, I'm using 'rake install'

**Comment by kingtosh** [comment]
same error i got on sierra.

**Comment by JK3Y** [comment]
@FIndustries @kingtosh i'm investigating this issue right now. In the meantime... the original Asepsis does work on High Sierra and below, this fork is specifically for macOS Mojave. I'll try to get backwards compatibility added.

**Comment by JK3Y** [comment]
@FIndustries @kingtosh I think I found a solution for you. Try this ` touch ~/.no-asepsis-os-restriction` I completely forgot about this bypass. You can find info here https://asepsis.binaryage.com/#sip
After running the command, try `rake install` again.

**Comment by JK3Y** [comment]
Closing. If this is still an issue I will reopen.
