### ISSUE TITLE
On 10.14.1 cause iCloud drive stop working

### ISSUE THREAD

**Issue by xiaozhuai** [JK3Y/asepsis#10]
On 10.14.1 cause iCloud drive stop working

**Comment by D-an-W** [comment]
Same here on 10.14, is this still developed?

**Comment by JK3Y** [comment]
Unfortunately I was never able to replicate this issue. I've updated the code in the repository, so maybe it will fix your problem.

**Comment by D-an-W** [comment]
Did / does iCloud Drive work ok for you then?

**Comment by xiaozhuai** [comment]
On 10.14.4 with iCloud drive, It's working perfectly now! Thank you very much! Please do not stop maintenance!

**Comment by JK3Y** [comment]
Good to hear! Don't worry, this is an important app for me so I plan to
keep it compatible with the latest macOS version.
Cheers.
