### ISSUE TITLE
Breaks DesktopServicesPriv.framework

### ISSUE THREAD

**Issue by raxod502** [JK3Y/asepsis#14]
Since installing this fork of Asepsis, opening several applications just gives me the following error:

```
dyld: Library not loaded: /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv
  Referenced from: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
  Reason: no suitable image found.  Did find:
	/System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv: mach-o, but wrong architecture
	/System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv: stat() failed with errno=45
	/System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv: mach-o, but wrong architecture
```

This didn't happen with vanilla Asepsis pre-Mojave. Reinstalling the OS fixes the issue, but also of course uninstalls Asepsis.

**Comment by JK3Y** [comment]
Please try the updated code in the repository. DesktopServicesPriv has been updated to fix these issues.

**Comment by woutgg** [comment]
First of all, thanks for forking and maintaining this wonderful program!

I'm also seeing this issue, also with the most recent commits.
(Actually, steam was crashing like in #16, which is the same error if I'm not mistaken, in fact all 32-bit apps seem to break).

So I tried uninstalling asepsis, which was troublesome due to `xcodebuild` being broken (by this same issue I think), but a reboot seems to fix this. After that, everything seems back to normal.

I haven't investigated this at all, but I'd be happy to test things if you like.

**Comment by D-an-W** [comment]
I am getting this issue with several programs even after using the updated build.

_Install Adobe Flash Player_ and _Cydia Impactor_ are two programs that won't launch with Asepsis installed, after updating to 10.14.5 Beta (18F118d) which naturally breaks Asepsis I tested them both before running the install_wrapper command and they worked fine but not after.

`Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x2] Wrong architecture

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv
  Referenced from: /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
  Reason: no suitable image found.  Did find:
	/System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv: mach-o, but wrong architecture
	/System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv: stat() failed with errno=1
	/System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv: mach-o, but wrong architecture`

**Comment by dactylo** [comment]
This is closed, but it's probably because Xcode 10 doesn't support 32 bit. The last version that does is 9.4.1.

I had the same issue, downgraded to 9.4.1, set the deployment target as 10.13, added i386 as a valid architecture, rebuilt asepsis, and now my old Adobe apps work.
