### ISSUE TITLE
BUG: Haven't told you that I love you.

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [JK3Y/asepsis#15]
I love you!

Please mark bug as fixed :) Yay, asepsis on Mojave. You fucking rock.

(Would've commented on your Reddit, but it's closed. Hope you ignored the "why you wanna duh dat?"  replies. This is fantastic. Hope you make it 10.15 compatible as well ;) Thank you!)

**Comment by JK3Y** [comment]
Haha thanks. When this no longer works with the current macOS then I update the code :)
