### ISSUE TITLE
Updating macOS?

### ISSUE THREAD

**Issue by D-an-W** [JK3Y/asepsis#19]
Hi and sorry for another "Issue",

Can I please ask when an update to macOS is released it usually breaks Asepsis, is your version simply fixed with the commands _asepsisctl uninstall_wrapper_ and 
_asepsisctl install_wrapper_ as with the official older releases?

**Comment by JK3Y** [comment]
That is correct. All the commands are the same as the original Asepsis (except that you no longer need to have the [.no-asepsis-os-restriction](https://asepsis.binaryage.com/#sip) file to install on newer OS versions.)
