### ISSUE TITLE
codesign error with 10.13

### ISSUE THREAD

**Issue by Jerry-Ma** [JK3Y/asepsis#3]
Hi,

Thank you very much for the update. I was able to build the app successfully but now I am having trouble installing the wrapper. The message I am getting is like:

```
---- START DRY RUN ----
> sudo rm -rf "/tmp/asepsis-codesign-dry-run"
> sudo mkdir -p "/tmp/asepsis-codesign-dry-run"
> sudo cp -a "/System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A" "/tmp/asepsis-codesign-dry-run"
> sudo "install_name_tool" -id "/tmp/asepsis-codesign-dry-run/A/DesktopServicesPriv" "/tmp/asepsis-codesign-dry-run/A/DesktopServicesPriv"
> sudo "/usr/bin/codesign" --file-list - --timestamp=none --force --sign - "/tmp/asepsis-codesign-dry-run/A/DesktopServicesPriv"
/tmp/asepsis-codesign-dry-run/A/DesktopServicesPriv: replacing existing signature
/tmp/asepsis-codesign-dry-run/A/DesktopServicesPriv: code object is not signed at all
In subcomponent: /private/tmp/asepsis-codesign-dry-run/A/DesktopServicesPriv.tbd
failed with code pid 8121 exit 1
> "/Library/Application Support/Asepsis/ctl/asepsisctl" install_updater
/Library/Application Support/Asepsis/ctl/lib/micro-optparse.rb:47: warning: constant ::Fixnum is deprecated
> sudo cp "/Library/Application Support/Asepsis/com.binaryage.asepsis.updater.plist" "/Library/LaunchAgents/com.binaryage.asepsis.updater.plist"
Asepsis installation encountered some failures, please inspect the command output.

```

Do you have any ideas?

**Comment by JK3Y** [comment]
I can look more at this tomorrow, but off the top of my head -- have you ran the commands 
`touch ~/.no-asepsis-os-restriction` and `touch ~/.asepsis-suppress-update-errors`?

**Comment by Jerry-Ma** [comment]
Yes, I did ran the command. The output line "START DRY RUN" is confusing, hence I run the commands by myself in the command line, but still the same error about the codesign.

One thing worth noticing is that I initially installed the official version, but had the same error message, which drove me to find your fork. But seems luck is not on my side :(

**Comment by JK3Y** [comment]
Well, up until 10.14 I've been using the method described [here](http://pixelcog.com/blog/2016/disable-ds_store-in-el-capitan/) to install Asepsis. I have gotten my fork running on 10.13 using the method described in the Readme, but the original application is compatible with that version so I'm not supporting anything less than 10.14. Try those instructions that I linked and let me know your results.

**Comment by Jerry-Ma** [comment]
The link you posted is where I learned about this software since I start using 10.12 on my old mbp. The same procedure fails on the codesign step on 10.13 with my new mbp. In any case, since 10.14 will be up the day after tomorrow I will be just wait for it, and hopefully the issue would be gone by then.

Thank you for the help!
