### ISSUE TITLE
Problem with icloud drive

### ISSUE THREAD

**Issue by wallneradam** [JK3Y/asepsis#5]
When asepsis installed my finder always complains about icoud drive and redirect me to icloud setup, but it is just crashing if I want to change something. If I click on desktop, finder hangs about 20-30 seconds. Nothing happens. If I uninstall asepsis everything works again. If I reinstall it, it will work until next reboot.

Any idea? Anyway, without icloud it seems to work just fine. Could you please help me to resolve this issue?

**Comment by JK3Y** [comment]
This is very bizarre... I've never had this issue. What steps are you taking to install Asepsis and what OS version are you using?

**Comment by wallneradam** [comment]
I installed it from source. It seems the problem was a corrupted XCode installation. It has not started at all. I removed it and reinstalled, and reinstalled Asepsis too, and now it seems to be fine. Thanks for your work with making it usable under Mojave. I really hate _DS_Store files!

**Comment by JK3Y** [comment]
Glad you got it working! I also hate the DS_Store files! :)

PS: Be sure to reinstall it on your system after any system updates with `asepsisctl uninstall_wrapper; asepsisctl install_wrapper;`. The part that I removed to make it compatible with Mojave is the update module. This means that it will **not** tell you when asepsis isn't working properly so it's on you to remember.
