### ISSUE TITLE
Finder won't open after installing asepsis

### ISSUE THREAD

**Issue by szmktk** [JK3Y/asepsis#6]
Hi,

I recently upgraded to Mojave and immediately after reboot I received a notification that asepsis is broken, so I reinstalled it like I do after every system update. But this time it didn’t work, so I started googling and found your fork! Thanks a lot for the good work :)

But I have a problem -  the finder app stopped working: 
<img width="501" alt="screenshot 2018-10-14 at 01 12 15" src="https://user-images.githubusercontent.com/23619042/46910935-b2440100-cf4e-11e8-935d-cf718eeb48ca.png">
The annoying thing is that window won’t go away – I can’t minimise it or get rid of it, and when I click any button then this annoying windows pops up again. I could do without finder as I’m not using it anyway, but this window is soooo frustrating that I’ll do anything to have it removed. 

Points to note:
- after installing asepsis I reenabled SIP
- then I uninstalled Xcode as I didn’t want 5.7 GB of space to be wasted indefinitely.

Do you have any clue what could I do to solve this finder issue or at least get rid of that bloody window? I already did steps 1 – 5 from this guide: https://discussions.apple.com/thread/8045079 (the remaining steps advise to reinstall the system but I’d like to avoid that for obvious reasons).

Thanks in advance

**Comment by JK3Y** [comment]
Hmm. Try completely uninstalling Asepsis `asepsisctl uninstall` reboot, reenable SIP (somehow I was able to get asepsis to install without disabling it) and follow the install instructions in the Readme. If you already built it using `rake build`, then just execute `rake install` and it should work

**Comment by JK3Y** [comment]
Ps: you don't have to install all of xcode btw. You just need the command line tools

**Comment by szmktk** [comment]
Please excuse my delayed answer, I was quite busy during weekend.

> Ps: you don't have to install all of xcode btw. You just need the command line tools

```
szmktk@sm-mbpro [~/Downloads/asepsis] ± master ✓                                                                                                                                                                                    [23:06:36]
> rake build
> xcodebuild -project Asepsis.xcodeproj -scheme build -configuration Release
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
Error[1]: build failed
```

It seems that I have to have Xcode installed (apart from the above output the readme says so).
I disabled SIP, ran `asepsisctl uninstall`, then re-enabled SIP & rebooted.

Next, I did  the following: 
`rake install`
`asepsisctl diagnose`
`asepsisctl uninstall_wrapper`
`csrutil status`
(see the output below)

So in my case the installation failed with SIP enabled. I will try to disable it again and try to install asepsis again.

```
szmktk@sm-mbpro [~/Downloads/asepsis] ± master ✓                                                                                                                                                                                    [23:11:59]
> rake install
> sudo rm -rf "/Library/Application Support/Asepsis"
> sudo cp -r "/Users/szmktk/Downloads/asepsis/bin/Asepsis/" "/Library/Application Support/Asepsis"
> "/Library/Application Support/Asepsis/ctl/asepsisctl" install
> "/Library/Application Support/Asepsis/ctl/asepsisctl" create_symlink
> mkdir -p /usr/local/bin
> sudo ln -Fs "/Library/Application Support/Asepsis/ctl/asepsisctl" "/usr/local/bin/asepsisctl"
> "/Library/Application Support/Asepsis/ctl/asepsisctl" make_dscage
> mkdir -p "/usr/local/.dscage"
> chmod 777 "/usr/local/.dscage"
> "/Library/Application Support/Asepsis/ctl/asepsisctl" install_daemon
> sudo cp "/Library/Application Support/Asepsis/com.binaryage.asepsis.daemon.plist" "/Library/LaunchDaemons/com.binaryage.asepsis.daemon.plist"
> sudo launchctl load "/Library/LaunchDaemons/com.binaryage.asepsis.daemon.plist"
> "/Library/Application Support/Asepsis/ctl/asepsisctl" launch_daemon
> sudo launchctl start "com.binaryage.asepsis.daemon"
> "/Library/Application Support/Asepsis/ctl/asepsisctl" install_wrapper

---- START DRY RUN ----
> sudo rm -rf "/tmp/asepsis-codesign-dry-run"
> sudo mkdir -p "/tmp/asepsis-codesign-dry-run"
> sudo cp -a "/System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A" "/tmp/asepsis-codesign-dry-run"
> sudo "install_name_tool" -id "/tmp/asepsis-codesign-dry-run/A/DesktopServicesPriv" "/tmp/asepsis-codesign-dry-run/A/DesktopServicesPriv"
> sudo "/usr/bin/codesign" --file-list - --timestamp=none --force --sign - "/tmp/asepsis-codesign-dry-run/A/DesktopServicesPriv"
/tmp/asepsis-codesign-dry-run/A/DesktopServicesPriv: replacing existing signature
/private/tmp/asepsis-codesign-dry-run/A/DesktopServicesPriv
/private/tmp/asepsis-codesign-dry-run/A/_CodeSignature/CodeResources
> codesign --verify "/tmp/asepsis-codesign-dry-run/A/DesktopServicesPriv"
> codesign --verify "/tmp/asepsis-codesign-dry-run/A"
> sudo rm -rf "/tmp/asepsis-codesign-dry-run"
> sudo mkdir -p "/tmp/asepsis-codesign-dry-run"
> sudo cp -a "/System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A" "/tmp/asepsis-codesign-dry-run"
> sudo cp "/Library/Application Support/Asepsis/DesktopServicesPrivWrapper" "/tmp/asepsis-codesign-dry-run/A/DesktopServicesPriv"
> sudo "/usr/bin/codesign" --file-list - --timestamp=none --force --sign - "/tmp/asepsis-codesign-dry-run/A"
/private/tmp/asepsis-codesign-dry-run/A/DesktopServicesPriv
/private/tmp/asepsis-codesign-dry-run/A/_CodeSignature/CodeResources
> codesign --verify "/tmp/asepsis-codesign-dry-run/A/DesktopServicesPriv"
> codesign --verify "/tmp/asepsis-codesign-dry-run/A"
> sudo rm -rf "/tmp/asepsis-codesign-dry-run"
---- END DRY RUN ----

wrapper framework seems to be installed (/System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A_ exists), to reinstall please run: "asepsisctl uninstall_wrapper" first
> "/Library/Application Support/Asepsis/ctl/asepsisctl" install_updater
> sudo cp "/Library/Application Support/Asepsis/com.binaryage.asepsis.updater.plist" "/Library/LaunchAgents/com.binaryage.asepsis.updater.plist"
Asepsis installation encountered some failures, please inspect the command output.

szmktk@sm-mbpro [~/Downloads/asepsis] ± master ✓                                                                                                                                                                                    [23:12:16]
> asepsisctl diagnose
DesktopServicesPriv (/System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv) is not properly installed.
  => Have you installed a system update recently? It might revert it back to the original version.

szmktk@sm-mbpro [~/Downloads/asepsis] ± master ✓                                                                                                                                                                                    [23:13:05]
> asepsisctl uninstall_wrapper
DesktopServicesPriv wrapper was replaced by system version since last Asepsis installation.
Usually this is the case when you install a system update which updates DesktopServicesPriv related files.
 => continuing in wrapper uninstallation, but skipping backup restoration.
> sudo "/usr/bin/codesign" --timestamp=none --force --sign - "/System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv"
/System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv: replacing existing signature
/System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv: Operation not permitted
failed with code pid 3243 exit 1


szmktk@sm-mbpro [~/Downloads/asepsis] ± master ✓                                                                                                                                                                                    [23:13:51]
1 > csrutil status
System Integrity Protection status: enabled.
```

**Comment by szmktk** [comment]
With SIP disabled I was able to install asepsis (though `rake build` command returned an error, but I was able to resolve it with `asepsisctl uninstall_wrapper && asepsisctl install_wrapper`), but then after rebooting to recovery and enabling SIP (and rebooting again) I got the same issue with finder. Same window, same error, but asepsis installed correctly. 

One thing that I noticed was when I disabled SIP (for the first time since I noticed the finder issue) then the issue was immediately gone. So after disabling SIP I had both finder & asepsis working, but the security of my system compromised >_<

Thank you in advance for the time you invest into keeping this project alive.

**Comment by JK3Y** [comment]
Did you try to install asepsis without disabling sip like I suggested? Also I know that totalfinder makes finder crash without sip disabled so if you also have that installed that could be the reason it's crashing when reenabled.

**Comment by szmktk** [comment]
Yep, I tired to install it with SIP enabled, see the output above (installation failed).
I also never used totalfinder.

**Comment by Aeneon** [comment]
Got the same Problem, Asepsis installed, but after trying to open any File Finder freezes and the System becomes unresponsive. Looks like Apple changed to many Things in "DesktopServicesPriv.framework" or Apple Events …

**Comment by JK3Y** [comment]
Unfortunately I'm not sure what the problem could be. I have reinstalled Asepsis on macOS Mojave again with no issues. If the installation steps do not work for you then unfortunately Asepsis may not be a possibility on your machine at this time.
